# Site settings
email: justinalfonso29@hotmail.com
baseurl:
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Jalfonze
description: Justin's Personal Blog
url: "https://jalfonze.com"
twitter_username:
default_img:

# Profile settings
name: Justin Alfonso
profile_img: [![dwuc3.md.jpg](https://i.lensdump.com/i/dwuc3.md.jpg)](https://lensdump.com/i/dwuc3)
profile: A dreamer born in Manila, Philippines but raised in Brighton, England. A musician by graduate, chef by trade and a traveller at heart. Meet, Live, Explore.
social:
  instagram: https://www.instagram.com/jalfonze
  facebook: https://www.facebook.com/jalfonze
  youtube: https://www.youtube.com/user/SluggerBrighton
  pinterest: https://www.pinterest.com.au/jalfonze1/

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Plugins
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
