# Site settings
email: justinalfonso29@hotmail.com
baseurl: "/jalfonze"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Jalfonze
description: Justin's Personal Blog
url: "https://jankdc.github.io/jalfonze"
twitter_username:
default_img:

# Profile settings
name: Justin Alfonso
profile_img: https://scontent-lhr3-1.xx.fbcdn.net/v/t31.0-8/15289064_10155245312175016_8888023215603392058_o.jpg?oh=1bb72f9703748c89453dd8e3b441e1d8&oe=5A63AE97
profile: Thoughts and travels by yours truly.
social:
  instagram: https://www.instagram.com/jalfonze
  facebook: https://www.facebook.com/jalfonze
  youtube: https://www.youtube.com/user/SluggerBrighton

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Plugins
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
